// <auto-generated />
using System;
using ApiMov.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiMov.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211004327_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ApiMov.Models.Mov", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DS_MOV")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DT_MOV")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TP_MOV")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("VL_MOV")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Mov");
                });
#pragma warning restore 612, 618
        }
    }
}
